//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.04 at 08:08:27 pm IST 
//


package com.pacs.payments.processor.xsd.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pacs.paymenta.processor package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pacs.paymenta.processor
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.PmtTpInf }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.PmtTpInf createDocumentCstmrCdtTrfInitnPmtInfPmtTpInf() {
        return new Document.CstmrCdtTrfInitn.PmtInf.PmtTpInf();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAgt }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAgt createDocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAgt() {
        return new Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAgt();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.Amt }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.Amt createDocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfAmt() {
        return new Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.Amt();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.GrpHdr }
     * 
     */
    public Document.CstmrCdtTrfInitn.GrpHdr createDocumentCstmrCdtTrfInitnGrpHdr() {
        return new Document.CstmrCdtTrfInitn.GrpHdr();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.Amt.InstdAmt }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.Amt.InstdAmt createDocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfAmtInstdAmt() {
        return new Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.Amt.InstdAmt();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf createDocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInf() {
        return new Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.DbtrAgt }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.DbtrAgt createDocumentCstmrCdtTrfInitnPmtInfDbtrAgt() {
        return new Document.CstmrCdtTrfInitn.PmtInf.DbtrAgt();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.Dbtr }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.Dbtr createDocumentCstmrCdtTrfInitnPmtInfDbtr() {
        return new Document.CstmrCdtTrfInitn.PmtInf.Dbtr();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn }
     * 
     */
    public Document.CstmrCdtTrfInitn createDocumentCstmrCdtTrfInitn() {
        return new Document.CstmrCdtTrfInitn();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.PmtId }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.PmtId createDocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfPmtId() {
        return new Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.PmtId();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf createDocumentCstmrCdtTrfInitnPmtInf() {
        return new Document.CstmrCdtTrfInitn.PmtInf();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.DbtrAgt.FinInstnId }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.DbtrAgt.FinInstnId createDocumentCstmrCdtTrfInitnPmtInfDbtrAgtFinInstnId() {
        return new Document.CstmrCdtTrfInitn.PmtInf.DbtrAgt.FinInstnId();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.DbtrAcct }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.DbtrAcct createDocumentCstmrCdtTrfInitnPmtInfDbtrAcct() {
        return new Document.CstmrCdtTrfInitn.PmtInf.DbtrAcct();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.Cdtr }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.Cdtr createDocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtr() {
        return new Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.Cdtr();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.PmtTpInf.SvcLvl }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.PmtTpInf.SvcLvl createDocumentCstmrCdtTrfInitnPmtInfPmtTpInfSvcLvl() {
        return new Document.CstmrCdtTrfInitn.PmtInf.PmtTpInf.SvcLvl();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAcct.Id }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAcct.Id createDocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAcctId() {
        return new Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAcct.Id();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.DbtrAcct.Id }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.DbtrAcct.Id createDocumentCstmrCdtTrfInitnPmtInfDbtrAcctId() {
        return new Document.CstmrCdtTrfInitn.PmtInf.DbtrAcct.Id();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.GrpHdr.InitgPty }
     * 
     */
    public Document.CstmrCdtTrfInitn.GrpHdr.InitgPty createDocumentCstmrCdtTrfInitnGrpHdrInitgPty() {
        return new Document.CstmrCdtTrfInitn.GrpHdr.InitgPty();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAgt.FinInstnId }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAgt.FinInstnId createDocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAgtFinInstnId() {
        return new Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAgt.FinInstnId();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAcct }
     * 
     */
    public Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAcct createDocumentCstmrCdtTrfInitnPmtInfCdtTrfTxInfCdtrAcct() {
        return new Document.CstmrCdtTrfInitn.PmtInf.CdtTrfTxInf.CdtrAcct();
    }

}
